[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PRISMA_GENERATE_DATAPROXY = "true"
  NPM_CONFIG_PACKAGE_LOCK = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Force npm instead of pnpm
[build.processing]
  skip_processing = false

# Ensure Prisma client is generated
[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true