[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Force npm instead of pnpm
[build.processing]
  skip_processing = false

# Ensure Prisma client is generated
[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true